<?php

return [
    [
        'user_id' => '1',
        'title' => 'Il tuo Sogno',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '85',
        'address' => 'Via della Scala, 3, Firenze',
        'latitude' => '43.7732317',
        'longitude' => '11.2465212',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Suite Ognissanti Firenze',
        'slug' => '',
        'rooms' => '6',
        'beds' => '1',
        'bathrooms' => '2',
        'square_meters' => '92',
        'address' => 'Via delle Porte Nuove, 2, Firenze',
        'latitude' => '43.7799492',
        'longitude' => '11.2403348',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Florence Santa Croce - Quiet',
        'slug' => '',
        'rooms' => '5',
        'beds' => '1',
        'bathrooms' => '2',
        'square_meters' => '80',
        'address' => 'Via Faenza, 71, Firenze',
        'latitude' => '43.777791',
        'longitude' => '11.251058',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Maison Brunelleschi - 50m dal Duomo, Ascensore',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '102',
        'address' => 'Via Rosina, 4, Firenze',
        'latitude' => '43.776646',
        'longitude' => '11.254669',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Traveller Nest: il nido dei viaggiatori',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '85',
        'address' => 'Via Ricasoli, 39, Firenze',
        'latitude' => '43.776442',
        'longitude' => '11.258267',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'APPARTAMENTO CENTRO STORICO FIRENZE',
        'slug' => '',
        'rooms' => '7',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '120',
        'address' => 'Via dei Servi, 15, Firenze',
        'latitude' => '43.774627',
        'longitude' => '11.2587816',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Love the Space',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '90',
        'address' => 'Via del Castellaccio, 13, Firenze',
        'latitude' => '43.7752982',
        'longitude' => '11.2576016',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'SUITE PICCOLO PRINCIPE Ognissanti square, Polimoda',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '65',
        'address' => 'Via della Pergola, 45, Firenze',
        'latitude' => '43.7749031',
        'longitude' => '11.262109',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Florence room',
        'slug' => '',
        'rooms' => '5',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '73',
        'address' => 'Via della Colonna, 11-5, Firenze',
        'latitude' => '43.7745931',
        'longitude' => '11.2645551',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Casa con grande terrazza Empoli',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '125',
        'address' => 'Via Giovan Battista Niccolini, 32, Firenze',
        'latitude' => '43.7731466',
        'longitude' => '11.2677746',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Punto nel Cuore - Appartamento',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'address' => 'Via Pietro Colletta, 2, Firenze',
        'latitude' => '43.7731466',
        'longitude' => '11.2677746',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Valia Florence Pitti accanto a Palazzo Pitti',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '95',
        'address' => 'Via Luca Landucci, 34, Firenze',
        'latitude' => '43.7722675',
        'longitude' => '11.2754472',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Dante&Beatrice Flat - Santa Maria Novella',
        'slug' => '',
        'rooms' => '9',
        'beds' => '3',
        'bathrooms' => '3',
        'square_meters' => '175',
        'address' => 'Via Giovanni Paisiello, 27, Firenze',
        'latitude' => '43.7817652',
        'longitude' => '11.2298328',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Apartment By Villa Il Mosaico',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '100',
        'address' => 'Via delle Porte Nuove, 15/a, Firenze',
        'latitude' => '43.7792043',
        'longitude' => '11.238969',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Elegante, Romantico, Confortevole Appartamento!',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '96',
        'address' => 'Via J. da Diacceto, 40, Firenze',
        'latitude' => '43.77849',
        'longitude' => '11.241015',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Moderno e Funzionale Monolocale',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'address' => 'Via Luigi Alamanni, 5, Firenze',
        'latitude' => '43.7769279',
        'longitude' => '11.2452965',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'IL MAGNIFICO - Home in Florence',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '102',
        'address' => 'Via del Alloro, 4, Firenze',
        'latitude' => '43.7739901',
        'longitude' => '11.2513614',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'I tre cipressi',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '86',
        'address' => 'Via dei Cerretani, 29 R, Firenze',
        'latitude' => '43.7733871',
        'longitude' => '11.2512322',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Bilocale - Santo Spirito',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '95',
        'address' => 'Via del Oriuolo, 66, Firenze',
        'latitude' => '43.771401',
        'longitude' => '11.2559798',
        'cover_image' => 'uploads/7NiVgqsQbR6MKP48T49CeP9BLbTNNVWMJyK1TdAG.jpg',
        'visible' => true
    ],
];
